//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunnyHomeCare.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyDbContext : DbContext
    {
        public MyDbContext()
            : base("name=MyDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Caretaker> Caretakers { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<PersonalContact> PersonalContacts { get; set; }
        public virtual DbSet<Request> Requests { get; set; }
        public virtual DbSet<Request_Patient> Request_Patient { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<ServiceContact> ServiceContacts { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Visit> Visits { get; set; }
    }
}
