//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunnyHomeCare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient_PersonalContact
    {
        public int PersonalContact { get; set; }
        public int PatientID { get; set; }
    
        public virtual PersonalContact PersonalContact1 { get; set; }
    }
}
