//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunnyHomeCare.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Visit
    {
        public int Id { get; set; }
        public int Patient_id { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{yyyy/MM/dd}")]
        public Nullable<System.DateTime> Date { get; set; }
        public int Caretaker_id { get; set; }
        public virtual Caretaker Caretaker { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
